---
- name: Write myid file.
  template: src=myid.j2 dest={{zookeeper_myid_path}}

- name: Get myid value
  shell: "cat {{zookeeper_myid_path}}"
  register: zookeeper_myid
  changed_when: False

- name: Make sure zookeeper is running and config is up-to-date
  docker_container:
    image: "{{zookeeper_docker_image}}"
    name: "{{zookeeper_name}}"
    volumes:
      - "{{zookeeper_data}}/data:/tmp/zookeeper"
    expose:
      - 2181
      - 2888
      - 3888
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    env:
      MYID: "{{ zookeeper_myid.stdout }}"
      SERVERS: "{{ groups['mesos-masters'] | join(',') }}"
    privileged: True
    net: host
    restart_policy: always
    state: reloaded
