---
- hosts: all
  sudo: yes

  tasks:
    - name: Set global cluster variable facts
      set_fact:
        zk_endpoint: "{{ groups['mesos-masters'] | join(':2181,') }}:2181"
        host_ip: "{{ vagrant_ip | default(ansible_eth0.ipv4.address) }}"

    - name: Set global mesos variable facts
      set_fact:
        mesos_zk: "zk://{{ zk_endpoint }}/mesos"

    - name: Set global marathon variable facts
      set_fact:
        marathon_host_servers: "{{ groups['mesos-masters'] }}"
        marathon_zk: "zk://{{ zk_endpoint }}/marathon"

  roles:
    - common

# Mesos masters
- hosts: mesos-masters
  gather_facts: false
  sudo: yes

  vars:
    - zookeeper_servers: "{{ groups['mesos-masters'] }}"
    - mesos_quorum: "{{ ((groups['mesos-masters'] | length) / 2) | round(0, 'ceil') | int }}"
    - mesos_logging_level: "WARNING"
    - marathon_logging_level: "warn"

  roles:
    - { role: docker, tags: [ 'docker' ], installation_type: traditional }
    - { role: zookeeper, tags: [ 'zookeeper' ] }
    - { role: mesosphere, tags: [ 'mesos' ], mesos_mode: master }
    - { role: marathon, tags: [ 'marathon'] }

# Mesos slaves
- hosts: mesos-slaves
  gather_facts: false
  sudo: yes

  vars:
    - mesos_executor_registration_timeout: 5mins
    - mesos_logging_level: "WARNING"
    - marathon_logging_level: "warn"

  roles:
    - { role: docker, tags: [ 'docker' ], installation_type: traditional }
    - { role: mesosphere, tags: [ 'mesos' ], mesos_mode: agent }
    - { role: haproxy_bridge, tags: [ 'haproxy-bridge'] }
