---
# Install Python 2 for Ansible to work correctly - needed on Ubuntu 16.04 due to no default installation
- hosts: all
  gather_facts: False
  become: true

  tasks:
  - name: Install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all
  become: true

  tasks:
    - name: Set global cluster variable facts
      set_fact:
        zk_endpoint: "{{ groups['mesos-masters'] | join(':2181,') }}:2181"
        host_ip: "{{ vagrant_ip | default(ansible_default_ipv4.address) }}"
      tags:
        - runtime

    - name: Set global mesos variable facts
      set_fact:
        mesos_zk: "zk://{{ zk_endpoint }}/mesos"
      tags:
        - runtime

    - name: Set global marathon variable facts
      set_fact:
        marathon_host_servers: "{{ groups['mesos-masters'] }}"
        marathon_zk: "zk://{{ zk_endpoint }}/marathon"
      tags:
        - runtime

# Mesos masters
- hosts: mesos-masters
  gather_facts: false
  become: true

  vars:
    - zookeeper_servers: "{{ groups['mesos-masters'] }}"
    - mesos_quorum: "{{ ((groups['mesos-masters'] | length) / 2) | round(0, 'ceil') | int }}"
    - mesos_logging_level: "INFO"
    - marathon_logging_level: "warn"

  roles:
    - common
    - { role: docker, tags: [ 'docker' ] }
    - { role: zookeeper, tags: [ 'zookeeper' ] }
    - { role: mesosphere, tags: [ 'mesos' ], mesos_mode: master }
    - { role: marathon, tags: [ 'marathon'] }

# Mesos slaves
- hosts: mesos-slaves
  gather_facts: false
  become: true

  vars:
    - mesos_executor_registration_timeout: 5mins
    - mesos_logging_level: "WARNING"
    - marathon_logging_level: "warn"

  roles:
    - common
    - { role: docker, tags: [ 'docker' ] }
    - { role: mesosphere, tags: [ 'mesos' ], mesos_mode: agent }
    - { role: haproxy_bridge, tags: [ 'haproxy-bridge'] }
