---
- hosts: all
  become: true
  gather_facts: False

# Mesos masters
- hosts: mesos-masters
  gather_facts: false
  sudo: yes

  vars:
    - zookeeper_servers: "{{ groups['mesos-masters'] }}"
    - mesos_quorum: "{{ ((groups['mesos-masters'] | length) / 2) | round(0, 'ceil') | int }}"
    - mesos_logging_level: "INFO"
    - mesos_install_mode: "master" # {master|slave|master-slave}
    - mesos_version: "1.2.0"

  roles:
    - common
    - { role: docker, tags: [ 'docker' ] }
    - { role: geerlingguy.java }
    - { role: AnsibleShipyard.ansible-zookeeper}
    - { role: JasonGiedymin.mesos, mesos_install_mode: master}

# Mesos slaves
- hosts: mesos-slaves
  gather_facts: false
  sudo: yes

  vars:
    - mesos_logging_level: "WARNING"
    - mesos_containerizers: "docker,mesos"
    - mesos_executor_timeout: "5mins"

  roles:
    - common
    - { role: docker, tags: [ 'docker' ] }
    - role: geerlingguy.java
    - role: JasonGiedymin.mesos
      mesos_install_mode: slave
