---
- name: Make sure mesos agent is running and config is up-to-date
  sudo: yes
  docker_container:
    image: "{{mesos_agent_docker_image}}"
    name: "{{mesos_agent_name}}"
    volumes:
      - "/sys:/sys"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/marathon:/var/marathon"
    ports:
      - "5051:5051"
    expose:
      - 5051
    env:
      MESOS_CONTAINERIZERS: "{{mesos_containerizers}}"
      MESOS_DOCKER_STOP_TIMEOUT: "{{mesos_docker_stop_timeout}}"
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "{{mesos_executor_registration_timeout}}"
      MESOS_HOSTNAME: "{{inventory_hostname}}"
      MESOS_IP: "{{host_ip}}"
      MESOS_ISOLATION: "{{mesos_isolation}}"
      MESOS_LOGGING_LEVEL: "{{mesos_logging_level}}"
      MESOS_LOG_DIR: "{{mesos_log_dir}}"
      MESOS_MASTER: "{{mesos_zk}}"
    privileged: True
    net: host
    restart_policy: always
    state: reloaded
