---
- name: Install packages to allow apt to use a repository over HTTPS
  apt: name={{item}} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - python-dev
    - libssl-dev
    - libffi-dev
    - software-properties-common
  become: true

- name: Get kernel version
  command: uname -r
  register: docker_kernel_version
  changed_when: False

- name: Install linux-image-extra-$(uname -r)
  apt:
    name: "linux-image-extra-{{docker_kernel_version.stdout}}"
    state: "present"

- name: Add Docker repository key
  apt_key:
    id: "{{ docker_keyserver_id }}"
    keyserver: "{{ docker_keyserver }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Alternative | Add Docker repository key
  shell: "curl -sSL {{ docker_keyserver }} | sudo apt-key add -"
  when: add_repository_key|failed

- name: HTTPS APT transport for Docker repository
  apt:
    name: apt-transport-https
    state: present

- name: add docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present

- name: Install (or update) docker package
  apt:
    name: "{{ docker_pkg_name }}"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: "{{ update_docker_package }}"
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"
